// Generates the CRX3 fixtures used by ExtensionBrowserTests. Node only — no Xcode needed, so the
// fixtures can be regenerated and inspected on any machine, and a signature test is a real
// signature test rather than a placeholder.
//
// Run:  node scripts/make_crx3_fixtures.js
// Out:  Tests/Fixtures/Packages/*.crx, *.zip  (committed; regenerating must be byte-identical)
//
// The key below is a throwaway generated for this repository. It signs test fixtures and nothing
// else. It is committed on purpose: the fixtures must be reproducible, and a signature fixture
// whose key is secret cannot be regenerated by anyone reviewing the test.
//
// Format reference: chromium/src/components/crx_file/{crx3.proto,crx_verifier.cc,crx_creator.cc}.

"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const TEST_PRIVATE_KEY_PEM = `-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCuM1tG3FxKN1YT
GdMjgzgkRU1zMFqLEpH/fYxC+US6TbGOhbMkWcwLM3kkHMCPKvqumTIikCAQFTfz
pzLANJKRyzXlnGpqyk3WXOGqIKQGUQvjoB21eqZvcndKvaFU+MWiOQZh/eFVgeLT
JDXO3afFHBIgs6kgbzdRehndmWdRUeJLuQ34XzqHkWprsLCLuu8p3tEt5M6N+kW2
G4josjs1UBpCRvtXp6OI4kG0v6RqufQ9mdahOOXARthVawNAIyQJQLHE0zC8MqGp
wJ54G+XO5asgT/dlrvwEKEhwjJySjObG82dBLCYu3oOrTHZFKPOHW6hjY6vacLOO
/pFEUhCFAgMBAAECggEAGKy3miLug6iw7YWz7YzRr/mNDerkeFyKB5l9+6KZRJZq
txhjFpwNleyVlTLpZ54b4g1bF6A4mm6W/VFKlAUeWb5iBQMR48yCGAISCOoUsbxb
JcPxUVptJs4c7Z5Mst+GBwNyzwCKIXWDborrgEDPWdEvFCi+pRR7znOwJD5tbwwh
HVyM+y/B/ma6g6p93lXhdbB40192UqP9O0nfx3ovh6KiGgdUqWmcjMd7VTgoc1rz
vjm1iiCqXzFIYblH2s9qbMjKOvBfL80WP7ip3vxbPXIDCVP7yyP2X03xoDhf8sHY
tJF1Ryr/SCbeKfrtnilp/qmnUqOeRnzNdsuc1nUUBQKBgQDoD/FJAFyXtT47J38m
hIOfX1BlCnIVy5E8h53XJYIfQbj6QbLKkJJ/2cP8fEt1HCnh7BDardlV0T7zpKTA
QkpzgTyVhhSV5UbAGaSRsR6VIMLIsZ6QMoQBykvpOi7pG1RU6BRAdsWno/6JLEZ3
6nq2xKUaAYb/3BoudsSD3gj+AwKBgQDAK3a85VkAzPR8jf18b/Ym9gwwMJEl2jNt
28+1FvDt7hIERNIcLzwGP5E1nrl30i2XIDbkn/JCeRefxlJWn8XZCW4sFPnWX8er
tbMoOfP10YnfVZjbIaKtI999dcs0sHMTePEGnkTki/lQNenZJmSoJPsO/qP5rQKo
oBIFLfmU1wKBgQDVI7doZlWk3UmgCUHGfdVqbp+nffWUwRjPMHwvW/rsfG/KIsd1
N13m4XsZjou7rzdkkm5Ue3JvWLVqECFlmD1LYzri1nhXyHK4A5VcXwKI08Mzk7fg
FxWZk1UvjEoDvh8xsMrQ/oXB2GTzVmAOyaUV8vz1Ksv0ehLt9BXATBGUQwKBgBpd
HCIYGNjKRXRdCnyq44s+0DdAQnl98PZOZLWEWzNZKPGa+3RQapy01dgUWX99vzFv
gvhklRjXgg0yaRNnQf5fk9TKX+gwJbWB7P1EzhpYT+Dq3liZybaVKFEO+vzUhEUU
n4R37B2qsl51twpKgR6sTCEngBl9ydKWe0Jop0frAoGBAIZAeo2rGoPFcFmn+gjN
5t3dA7AOBbOhblXcMwxT0ZcyoOjW+iAZDeA3/OV4o90hXSGHyZVhZyUc1GV333gc
xZy9jiaD2KnTxc/likHHLTJxeoULS9Kg56cBqoutalJeI2h2wUX9DAmj6apIE3k3
5nrscu3cP8sUHmpVV02NHwld
-----END PRIVATE KEY-----`;

const OUT_DIR = path.join(__dirname, "..", "Tests", "Fixtures", "Packages");

// ---------------------------------------------------------------- ZIP (stored)

// A minimal store-only ZIP writer. No dependency, and deterministic: timestamps are fixed, so
// regenerating a fixture is byte-identical to the committed one and any diff means a real change.
function crc32(buffer) {
  let table = crc32.table;
  if (!table) {
    table = crc32.table = new Int32Array(256);
    for (let i = 0; i < 256; i += 1) {
      let c = i;
      for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      table[i] = c;
    }
  }
  let crc = -1;
  for (let i = 0; i < buffer.length; i += 1) crc = (crc >>> 8) ^ table[(crc ^ buffer[i]) & 0xff];
  return (crc ^ -1) >>> 0;
}

function buildZip(entries) {
  const locals = [];
  const centrals = [];
  let offset = 0;

  for (const entry of entries) {
    const name = Buffer.from(entry.name, "utf8");
    const data = Buffer.from(entry.data, "utf8");
    const sum = crc32(data);

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0); // local file header signature
    local.writeUInt16LE(20, 4); // version needed to extract
    local.writeUInt16LE(0, 6); // flags
    local.writeUInt16LE(0, 8); // method 0 = stored
    local.writeUInt16LE(0, 10); // modification time, fixed
    local.writeUInt16LE(0x21, 12); // modification date, fixed (1980-01-01)
    local.writeUInt32LE(sum, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28);
    locals.push(local, name, data);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0); // central directory header signature
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0, 8);
    central.writeUInt16LE(0, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(0x21, 14);
    central.writeUInt32LE(sum, 16);
    central.writeUInt32LE(data.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt16LE(0, 30);
    central.writeUInt16LE(0, 32);
    central.writeUInt16LE(0, 34);
    central.writeUInt16LE(0, 36);
    central.writeUInt32LE(0, 38);
    central.writeUInt32LE(offset, 42);
    centrals.push(central, name);

    offset += local.length + name.length + data.length;
  }

  const centralBytes = Buffer.concat(centrals);
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0); // end of central directory signature
  eocd.writeUInt16LE(entries.length, 8);
  eocd.writeUInt16LE(entries.length, 10);
  eocd.writeUInt32LE(centralBytes.length, 12);
  eocd.writeUInt32LE(offset, 16);
  return Buffer.concat([Buffer.concat(locals), centralBytes, eocd]);
}

// ----------------------------------------------------------- protobuf (writer)

function varint(value) {
  const bytes = [];
  let remaining = value;
  for (;;) {
    const byte = remaining & 0x7f;
    remaining >>>= 7;
    if (remaining > 0) {
      bytes.push(byte | 0x80);
    } else {
      bytes.push(byte);
      break;
    }
  }
  return Buffer.from(bytes);
}

// Field 10000 needs a three-byte tag (82 f1 04). A parser that assumes one-byte tags desyncs right
// here, which is why the Swift reader carries a test for exactly this field.
function lengthDelimited(fieldNumber, payload) {
  return Buffer.concat([varint((fieldNumber << 3) | 2), varint(payload.length), payload]);
}

// ------------------------------------------------------------------------ CRX3

// "CRX3 SignedData" followed by one NUL: sixteen bytes. The NUL is appended as a byte rather than
// embedded in the literal so that no control character appears in this source file.
const SIGNATURE_CONTEXT = Buffer.concat([
  Buffer.from("CRX3 SignedData", "ascii"),
  Buffer.from([0x00]),
]);
const ALPHABET = "abcdefghijklmnop";

// PK 05 06, PK 06 07, PK 06 06 — the tokens a ZIP reader scans for when locating the end of the
// central directory. Chromium refuses a CRX whose header contains one; so does the Swift reader.
const EOCD_TOKENS = [
  Buffer.from([0x50, 0x4b, 0x05, 0x06]),
  Buffer.from([0x50, 0x4b, 0x06, 0x07]),
  Buffer.from([0x50, 0x4b, 0x06, 0x06]),
];

function crxIdBytes(spki) {
  return crypto.createHash("sha256").update(spki).digest().subarray(0, 16);
}

function alphabetIdentifier(idBytes) {
  let out = "";
  for (const byte of idBytes) out += ALPHABET[byte >> 4] + ALPHABET[byte & 0x0f];
  return out;
}

// The length prefix covers signed_header_data, not the outer header. Getting that wrong produces a
// signature that verifies against nothing.
function signedPayload(signedHeaderData, archive) {
  const length = Buffer.alloc(4);
  length.writeUInt32LE(signedHeaderData.length, 0);
  return Buffer.concat([SIGNATURE_CONTEXT, length, signedHeaderData, archive]);
}

function buildCRX3(archive, options) {
  const opts = options || {};
  const privateKey = crypto.createPrivateKey(TEST_PRIVATE_KEY_PEM);
  const spki = crypto.createPublicKey(privateKey).export({ type: "spki", format: "der" });

  const declaredId = opts.declaredIdBytes || crxIdBytes(spki);
  const signedHeaderData = lengthDelimited(1, declaredId); // SignedData { bytes crx_id = 1 }

  // Signed over the archive, so flipping one payload byte after signing must break verification.
  const toSign = signedPayload(signedHeaderData, opts.signedArchive || archive);
  let signature = crypto.createSign("sha256").update(toSign).sign(privateKey); // PKCS#1 v1.5

  if (opts.corruptSignature) {
    signature = Buffer.from(signature);
    signature[0] ^= 0xff;
  }

  const proof = Buffer.concat([lengthDelimited(1, spki), lengthDelimited(2, signature)]);
  const header = Buffer.concat([
    lengthDelimited(2, proof), // sha256_with_rsa
    lengthDelimited(10000, signedHeaderData),
  ]);

  for (const token of EOCD_TOKENS) {
    if (header.includes(token)) {
      throw new Error("header contains a ZIP end-of-central-directory token; regenerate");
    }
  }

  const prefix = Buffer.alloc(12);
  prefix.write(opts.magic || "Cr24", 0, 4, "ascii");
  prefix.writeUInt32LE(opts.version === undefined ? 3 : opts.version, 4);
  prefix.writeUInt32LE(opts.headerLength === undefined ? header.length : opts.headerLength, 8);
  return {
    bytes: Buffer.concat([prefix, header, archive]),
    spki: spki,
    declaredId: declaredId,
    headerLength: header.length,
  };
}

// CRX2: magic, version 2, key length, signature length, key, signature, ZIP. Generated only so the
// reader can be shown rejecting it. Read offset 8 of one of these as a CRX3 header length and you
// get the public key length instead — the misparse that follows is quiet rather than loud.
function buildCRX2(archive) {
  const privateKey = crypto.createPrivateKey(TEST_PRIVATE_KEY_PEM);
  const spki = crypto.createPublicKey(privateKey).export({ type: "spki", format: "der" });
  const signature = crypto.createSign("sha1").update(archive).sign(privateKey);
  const prefix = Buffer.alloc(16);
  prefix.write("Cr24", 0, 4, "ascii");
  prefix.writeUInt32LE(2, 4);
  prefix.writeUInt32LE(spki.length, 8);
  prefix.writeUInt32LE(signature.length, 12);
  return Buffer.concat([prefix, spki, signature, archive]);
}

// ------------------------------------------------------------------- fixtures

function manifest(name) {
  return JSON.stringify(
    {
      manifest_version: 3,
      name: name,
      version: "1.0",
      description: "Fixture extension for KiwiX installer tests.",
      permissions: ["storage"],
      host_permissions: ["https://example.com/*"],
    },
    null,
    2
  );
}

function payloadZip(name) {
  return buildZip([
    { name: "manifest.json", data: manifest(name) },
    { name: "content.js", data: "// fixture content script\n" },
    { name: "assets/note.txt", data: "fixture asset\n" },
  ]);
}

// A wrapper directory instead of a flat root. Packagers zip the containing folder constantly, so
// the installer has to unwrap exactly one level -- and prove it does.
function nestedZip(name) {
  return buildZip([
    { name: "wrapper/manifest.json", data: manifest(name) },
    { name: "wrapper/content.js", data: "// fixture content script\n" },
  ]);
}

// A structurally valid archive with no manifest anywhere. Rejected after extraction, which is the
// only path that leaves a staging directory behind if cleanup is wrong.
function manifestlessZip() {
  return buildZip([
    { name: "readme.txt", data: "no manifest here\n" },
    { name: "scripts/content.js", data: "// orphan\n" },
  ]);
}

function write(fileName, bytes) {
  const target = path.join(OUT_DIR, fileName);
  fs.writeFileSync(target, bytes);
  const digest = crypto.createHash("sha256").update(bytes).digest("hex").slice(0, 16);
  console.log(
    `  ${fileName.padEnd(24)} ${String(bytes.length).padStart(7)} bytes  sha256:${digest}`
  );
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  console.log(`writing fixtures to ${OUT_DIR}`);

  const archive = payloadZip("KiwiX Fixture Extension");
  const valid = buildCRX3(archive);
  const identifier = alphabetIdentifier(valid.declaredId);

  // Positive: a genuine RSA-2048 PKCS#1 v1.5 SHA-256 signature over the real payload.
  write("valid.crx", valid.bytes);

  // Signature is valid for a *different* archive: the header verifies in isolation but the payload
  // it is attached to was swapped after signing.
  write(
    "tampered-payload.crx",
    buildCRX3(payloadZip("Swapped Payload"), { signedArchive: archive }).bytes
  );

  // Structurally perfect, one flipped signature byte. Distinguishes "broken" from "absent".
  write("wrong-signature.crx", buildCRX3(archive, { corruptSignature: true }).bytes);

  // crx_id in signed_header_data does not match SHA-256(SPKI)[0..16]. The signature over it is
  // genuine, so only the id comparison catches this one.
  const wrongId = Buffer.from(valid.declaredId);
  wrongId[0] ^= 0xff;
  write("mismatched-id.crx", buildCRX3(archive, { declaredIdBytes: wrongId }).bytes);

  // Same "Cr24" magic, version 2. Must be rejected on the version word, not silently misparsed.
  write("crx2.crx", buildCRX2(archive));

  // Declared header length runs past the end of the file.
  write("truncated-header.crx", buildCRX3(archive, { headerLength: 0x7fffffff }).bytes);

  // Header length claims zero: no proofs, no signed header data to compare an id against.
  write("zero-header.crx", buildCRX3(archive, { headerLength: 0 }).bytes);

  // Not a CRX at all — the unsigned path, which installs behind a two-step confirmation.
  write("unsigned.zip", archive);

  // Everything under one wrapper directory: the installer must find manifest.json one level down.
  write("nested.zip", nestedZip("KiwiX Nested Fixture"));

  // Valid ZIP, no manifest. Must be rejected without leaving a staging directory behind.
  write("no-manifest.zip", manifestlessZip());

  console.log(`\nderived extension id: ${identifier}`);
  console.log(`crx_id (hex):         ${valid.declaredId.toString("hex")}`);
  console.log(`header length:        ${valid.headerLength}`);
}

main();
